[workspace]
members = ["crates/dashboard-core", "crates/dashboard-host", "crates/dashboard-plugin"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[workspace.dependencies]
dashboard-core = { path = "crates/dashboard-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
